#hooks:
#  pre-init-hook:
#  post-init-hook:
#  pre-exit-hook:
#  post-exit-hook:

http-address: "192.0.2.1"
http-port: "8080"
controller-uri: "http://192.0.2.2:8080"
backbone-ip: "fd00::01"

linux-headend-set-source-address: "fd00:51D5:0000::"
gtp4-headend-prefix: "10.0.200.3/32"
headends:
  - name: "gtp4 to sr"
    to: "10.0.200.3/32"
    provider: "NextMN"
    behavior: "H.M.GTP4.D"
    policy:
      - match:
          teid: 0x0001
        bsid:
          bsid-prefix: "fd00:51D5:000:2::/80"
          segments-list:
            - "fd00:51D5:0000:3::"
            - "fd00:51D5:0000:4::"
    source-address-prefix: "fd00:51D5:000:1:9999::/80"
  - name: "linux test"
    to: "10.0.100.0/24"
    provider: "Linux"
    behavior: "H.Encaps"
    policy:
      - bsid:
          segments-list:
            - "fd00:51D5:0000:2::"
            - "fd00:51D5:0000:3::"

locator: "fd00:51D5:0000:1::/64"
endpoints:
  - prefix: "fd00:51D5:0000:1:11::/80"
    behavior: "End.DX4"
    provider: "Linux"
  - prefix: "fd00:51D5:0000:1:1::/80"
    behavior: "End"
    provider: "Linux"
logger:
  level: "info" # trace, debug, info, warning, error, fatal, or panic
