# This is a basic workflow to help you get started with Actions

name: CI 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
    go_build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v5
        - name: Install depends
          run: go get .
        - name: Build
          run: go build -v ./...
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install depends
          run: sudo apt-get install -qy make git && make dev-install
        - name: Run SQL lint and check generated files
          run: make lint
        - name: Run postgres
          run: make test-postgres
